language: elixir
elixir: 1.9.2
otp_release: 22.1
services:
  - postgresql
before_install:
  - chmod +x deploy.sh
before_script:
  - PGPASSWORD=postgres psql -c 'create database lost_pets_test;' -U postgres
script:
  - mix test && ./deploy.sh
